### ISSUE TITLE
Add example for damage on critical hit with strength modifier

### ISSUE THREAD

**Issue by david-dasilva** [PuttingTheDnDInTDD/EverCraft-Kata#6]
Hi!

Thanks for the kata, I love the theme!

One point is not clear for me though, maybe it could use a little example in the feature : 

**How many points of damage is dealt on a critical Hit exactly?**

Feature "_Character Can Be Damaged_" states :

> If attack is successful, other character takes 1 point of damage when hit
> If a roll is a natural 20 then a critical hit is dealt and the damage is doubled

At this point it means a critical deals 2 damage : `1 * 2 = 2`
But then feature "_Character Ability Modifiers Modify Attributes_" states :
>add Strength modifier to:
> - attack roll and damage dealt
> - double Strength modifier on critical hits

Does that means that an attacker with a Strength modifier of +4 deals :
- `(1 * 2) + (+4 * 2) = 10` so doubling the base attack damage, and then doubling the modifier? Or
- `1  + (+4 * 2) =  9` so doubling only the modifier but not the base damage ?

Thanks in advance

**Comment by walterg2** [comment]
Hi @david-dasilva, thanks for the kind words regarding this kata. @guyroyse and I had a ton of fun making it.

As for your question, the requirements are written as such on purpose. When developers receive requirements from the business, there is typically some ambiguity inherently in them because the writer is also (commonly) the subject matter expert on the solution. When this is given through a workshop, we are usually there to "play" the role of the product owner and answer these types of questions with those in attendance and we are aware that this does leave some questions for those working the kata on their own.

As for your direct question regarding how the Strength Modifier is applied when dealing damage, since the initial requirement of a critical hit doubles the damage was not changed with this new rule, your first bullet point would be the most accurate representation for how to apply the new requirement.

**Comment by david-dasilva** [comment]
Thank you for you quick answer!
